language: ruby
rvm:
  - 2.2.0
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cp config/database.travis.yml config/database.yml
script:
  - bundle exec rake db:create db:test:load
  - bundle exec rspec spec
