modules:
  - name: 'my_shop_b'

paths:
  my_shop_b: my_shop_b
  jquery: 'sources/jquery/jquery'
  backbone: 'sources/backbone/backbone'
  underscore: 'sources/underscore/underscore'
  text: 'sources/text'
  precompiledTemplates: 'viktor/my_shop_b/precompiledTemplates'
  my_shop_b_router: 'viktor/my_shop_b/router'
  my_shop_b_controller: 'viktor/my_shop_b/controller'
  my_shop_b_base_view: 'viktor/my_shop_b/base/baseView'
  my_shop_b_base_model: 'viktor/my_shop_b/base/baseModel'
  my_shop_b_base_collection: 'viktor/my_shop_b/base/baseCollection'

hbs:
  i18n: false
  templateExtension: 'hbs'
  helperDirectory: 'templates/helpers/'

packages:
  - name: 'shop_b'
    location: 'viktor/my_shop_b/components/shop'
    main: 'index'

shim:
  backbone:
    deps: ['jquery', 'underscore']
